### ISSUE TITLE
[ENH]: Use secrets for `myjd.password`

### ISSUE THREAD

**Issue by Brice187** [pmoscode-helm/jdownloader2#39]
### Description

currently the credentials are stored as plain-text secret in `values.yaml`. If you have a public gitops repo you can not use this chart because confidential information gets exposed.

Enhancement:
- add the possibility to reference a Kubernetes secret to benefit from tools like `sealed secrets` by bitnami

**Comment by pmoscode** [comment]
For my home lab, it was ok.
But here it comes. :)
